### ISSUE TITLE
Unify Dictionary.TryGet and Dictionary.Contains

### ISSUE THREAD

**Issue by Manuzor** [Manuzor/krepel-d#16]
See https://github.com/Manuzor/krepel-d/pull/14#discussion-diff-57527481

**Comment by Manuzor** [comment]
I've implemented this as `Dictionary.Get` which returns a pointer to the value within the dictionary if it exists, otherwise it returns a given fallback value which is `null` by default.

I've also added a `GetOrCreate` function, which acts just like `Get` but instead of returning `null`, it creates a new key-value pair and returns the pointer to the value.

**Comment by Manuzor** [comment]
I've used this successfully in the input code and am quite happy with it. @pampersrocker thoughts, or can we close this?

**Comment by pampersrocker** [comment]
I guess so
