### ISSUE TITLE
Input System

### ISSUE THREAD

**Issue by Manuzor** [Manuzor/krepel-d#26]
- [x] Make it possible to map buttons to axes. => _Use `AddSlotMapping` with a scaling value._
- [x] Rename `AddTrigger` to something more descriptive such as `MapInputSlots`. => _`AddSlotMapping`_
- [x] Support multiple slot mappings, i.e. some action `"Foo"` can be triggered by `Keyboard.W` or `Mouse.LeftButton`. => _Done._

**Comment by pampersrocker** [comment]
Is now in #29
