### ISSUE TITLE
Allocation Overlap

### ISSUE THREAD

**Issue by pampersrocker** [Manuzor/krepel-d#30]
In the following commit there is a allocation overlap between an Array and a Win32File

https://github.com/Manuzor/krepel-d/commit/0fdbb71f09423d9cf8cd2f77c6febecb4e9652ee

**Comment by pampersrocker** [comment]
Some debugging stuff around this is now in 17d2bcf  on branch `overlap-memory-bug` in the `win32_experiments_tests` build

**Comment by pampersrocker** [comment]
![image](https://cloud.githubusercontent.com/assets/1851043/15453906/6f91050c-2027-11e6-9828-f4856788367d.png)

**Comment by Manuzor** [comment]
I only managed to get a short look at things but I suspect it's the array copy. I think I either haven't fully grasped yet how D's struct copying works and/or `krepel.memory.construction` is doesn't quite work as expected. In either case, we need more tests, especially for the array. I had problems with copying them before when implementing input stuff.

**Comment by pampersrocker** [comment]
Fixed in https://github.com/Manuzor/krepel-d/commit/df092ac1f6888c19be67716c9dfc344532898c00 and https://github.com/Manuzor/krepel-d/commit/1f4efc3bc2e2fd4b735a301b9b089d7d9b0f8de7
